stages:
  - deploy

deploy:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install -y openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SERVER_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - ssh-keyscan -p 2023 128.199.218.8 >> ~/.ssh/known_hosts
  script:
    - ssh -p 2023 gitlab@128.199.218.8 "cd /var/docker/dev-backend.rumahaqiqah.co.id && git pull"
    - ssh -p 2023 gitlab@128.199.218.8 "cd /docker/dev-backend.rumahaqiqah.co.id && docker-compose restart"
#stage 1
